revision = '8ce5efa85226'
down_revision = '5d59acc6164c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

    # Add the user_id column to the tasks table
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # Create the foreign key constraint
    op.create_foreign_key('fk_tasks_user_id_users', 'tasks', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # Remove the foreign key constraint
    op.drop_constraint('fk_tasks_user_id_users', 'tasks', type_='foreignkey')

    # Remove the user_id column from the tasks table
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('user_id')
